#!/bin/bash

set -euo pipefail

# === Functions ===
check_root() {
    if [[ $EUID -ne 0 ]]; then
        echo "This script must be run as root. Use sudo."
        exit 1
    fi
}

install_msmtp() {
    if ! command -v msmtp >/dev/null 2>&1; then
        echo "🔧 msmtp not found. Installing..."
        if command -v apt >/dev/null; then
            apt update && apt install -y msmtp
        elif command -v dnf >/dev/null; then
            dnf install -y msmtp
        elif command -v yum >/dev/null; then
            yum install -y msmtp
        elif command -v pacman >/dev/null; then
            pacman -Sy msmtp
        else
            echo "Unsupported package manager. Install msmtp manually."
            exit 1
        fi
    else
        echo "msmtp is already installed."
    fi
}

configure_msmtp() {
    MSMTP_CONFIG="/etc/msmtprc"

    # Skip if already configured
    if [[ -f "$MSMTP_CONFIG" ]] && grep -q "account default" "$MSMTP_CONFIG"; then
        echo "msmtp already configured at $MSMTP_CONFIG"
        return
    fi

    echo ""
    echo "Configure msmtp for sending alert emails"
    read -rp "Enter SMTP server (e.g., smtp.gmail.com): " smtp_server
    read -rp "Enter SMTP port (e.g., 587): " smtp_port
    read -rp "Enter your email address: " smtp_user
    read -rsp "Enter your email password or app password: " smtp_pass
    echo ""

    cat > "$MSMTP_CONFIG" <<EOF
# msmtp config generated by install_monitor.sh

defaults
auth           on
tls            on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
logfile        /var/log/msmtp.log

account        default
host           $smtp_server
port           $smtp_port
from           $smtp_user
user           $smtp_user
password       $smtp_pass
account default : default
EOF

    chmod 600 "$MSMTP_CONFIG"
    echo "msmtp configured at $MSMTP_CONFIG"
}


configure_log_location() {
    echo ""
    read -rp "Enter full path for the log file [default: /var/log/resource_monitor.log]: " user_log_file
    LOG_FILE="${user_log_file:-/var/log/resource_monitor.log}"
    
    echo "Updating log file path in config.sh..."

    if [[ ! -f config.sh ]]; then
        echo "❌ config.sh not found in current directory. Please place this script in the same folder as config.sh."
        exit 1
    fi

    sed -i "s|^LOG_FILE=.*|LOG_FILE=\"$LOG_FILE\"|" config.sh
    echo "Log file path set to $LOG_FILE"
}

setup_systemd_service() {
    echo ""
    read -rp "➕ Do you want to add resource_monitor4.sh as a systemd service? [y/N]: " choice
    case "$choice" in
        [yY][eE][sS]|[yY])
            SERVICE_NAME="resource_monitor"
            SCRIPT_PATH="$(realpath ./resource_monitor4.sh)"
            SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"

            cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=Resource Monitor Script
After=network.target

[Service]
Type=simple
ExecStart=$SCRIPT_PATH
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

            chmod 644 "$SERVICE_FILE"
            systemctl daemon-reexec
            systemctl daemon-reload
            systemctl enable "$SERVICE_NAME"
            systemctl start "$SERVICE_NAME"

            echo "Service '$SERVICE_NAME' installed and started."
            ;;
        *)
            echo "ℹSkipped systemd setup."
            ;;
    esac
}

# === Main ===
echo "Starting Resource Monitor Installer"
check_root
install_msmtp
configure_msmtp
configure_log_location
setup_systemd_service

echo ""
echo "All done. Your system is now ready to monitor resources and send alerts."
